import { ArrowLeft } from "lucide-react";
import { Link } from "react-router";

export default function Page() {
  return (
    <>
      <title>Terms of Service - Linecraft</title>
      <div className="min-h-screen bg-background">
        <div className="max-w-3xl mx-auto px-4 py-16">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>

          <h1 className="text-4xl font-bold tracking-tight mb-8">
            Terms of Service
          </h1>

          <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground">
            <p className="text-lg">
              Last updated:{" "}
              {new Date().toLocaleDateString("en-US", {
                month: "long",
                day: "numeric",
                year: "numeric",
              })}
            </p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing and using Linecraft ("the Service"), you agree to
                be bound by these Terms of Service. If you do not agree to these
                terms, please do not use the Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                2. Description of Service
              </h2>
              <p>
                Linecraft is a Telegram-based AI assistant that helps users
                generate conversation starters, pickup lines, replies, and date
                ideas based on uploaded dating profiles or conversations.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                3. User Responsibilities
              </h2>
              <p>You agree to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use the Service only for lawful purposes</li>
                <li>Not use the Service to harass, stalk, or harm others</li>
                <li>Not upload content that violates others' privacy rights</li>
                <li>
                  Be solely responsible for how you use the generated content
                </li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                4. Content and Intellectual Property
              </h2>
              <p>
                Content generated by Linecraft is provided for your personal
                use. We do not claim ownership of the content you upload or the
                responses generated for you.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                5. Disclaimer
              </h2>
              <p>
                The Service is provided "as is" without warranties of any kind.
                We do not guarantee that the generated content will lead to any
                specific outcomes. Use of generated content is at your own
                discretion and risk.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                6. Limitation of Liability
              </h2>
              <p>
                Linecraft shall not be liable for any indirect, incidental,
                special, consequential, or punitive damages resulting from your
                use of the Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                7. Changes to Terms
              </h2>
              <p>
                We reserve the right to modify these terms at any time.
                Continued use of the Service after changes constitutes
                acceptance of the new terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">
                8. Contact
              </h2>
              <p>
                For questions about these Terms, please reach out through our
                Telegram bot.
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
